before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopenmpi-dev
  - sudo apt-get install -y libfftw3-dev
  - sudo apt-get install -y libopenblas-dev liblapack-dev
  - sudo apt-get install gfortran
language: cpp
compiler: mpicxx
script:
  - ./autogen.sh
  - ./configure
  - make
